# mqtt properties
mqtt.host=${MQTT_HOST}
mqtt.port=${MQTT_PORT}
mqtt.username=${MQTT_USERNAME}
mqtt.password=${MQTT_PASSWORD}
mqtt.topic=factory/sensors/

# db connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/iotappdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# table created by Hibernate
spring.jpa.hibernate.ddl-auto=update