# mqtt properties
mqtt.host=06389da49a8840caadd2c6ba77d9235d.s1.eu.hivemq.cloud
mqtt.port=8883
mqtt.username=gulnur-test
mqtt.password=test.
mqtt.topic=factory/sensors/

# db connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/iotappdb
spring.datasource.username=admin
spring.datasource.password=admin
# table created by Hibernate
spring.jpa.hibernate.ddl-auto=update